[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

lib_extra_dirs =
    ../LumaSense/lib

board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = default.csv
board_build.flash_mode = dio
board_build.f_flash = 80000000L

build_flags =
    -D HYDROSENSE_PLATFORM_ESP32S3
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1