[env:esp32-s3-super-mini]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; ESP32-S3 Super Mini = 4 MB Flash
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304

; Wymuszamy tablicę partycji pasującą do 4 MB
board_build.partitions = default.csv

; Flash
board_build.flash_mode = dio

; USB-C / natywne USB ESP32-S3
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_deps =
    adafruit/RTClib
    knolleary/PubSubClient @ ^2.8
    symlink://../aquaOneCore