[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    symlink://../aquaOneCore
