[platformio]
default_envs = web_spike_async, web_spike_idf
src_dir = src

[env]
platform = platformio/espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:web_spike_baseline]
build_src_filter =
    -<*>
    +<baseline.cpp>

[env:web_spike_async]
build_src_filter =
    -<*>
    +<async_candidate.cpp>
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps =
    ESP32Async/ESPAsyncWebServer@3.6.0
    ESP32Async/AsyncTCP@3.3.2

[env:web_spike_idf]
board = esp32-s3-devkitc-1
board_build.flash_size = 4MB
board_build.partitions = default.csv
board_upload.flash_size = 4MB
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1 -I.pio
build_src_filter =
    -<*>
    +<idf_candidate.cpp>
