#include "TimeManager.h"
#include "app_config.h"
#include <WiFi.h>
#include <time.h>
#include <Wire.h>
#include <esp_sntp.h>
namespace { constexpr uint32_t MIN_VALID_TIMESTAMP=1700000000UL; constexpr uint8_t DS3231_ADDRESS=0x68; }
TimeManager* TimeManager::instance=nullptr;
bool TimeManager::begin(){ Wire.begin(PIN_I2C_SDA,PIN_I2C_SCL); Wire.setTimeOut(100); rtcFoundAtBoot=rtc.begin(); if(!rtcFoundAtBoot) Serial.println("[RTC] DS3231 nie znaleziony"); else { pollRtc(true); if(rtcOk){ Serial.println("[RTC] DS3231 OK"); if(rtc.lostPower()) Serial.println("[RTC] Uwaga: RTC utracil zasilanie / czas moze byc niepoprawny"); } else Serial.println("[RTC] DS3231 znaleziony, ale pierwszy odczyt nieudany"); } instance=this; sntp_set_time_sync_notification_cb(onNtpSync); sntp_set_sync_interval(NTP_SYNC_INTERVAL_MS); startNtpSync(); return rtcOk; }
void TimeManager::startNtpSync(){ lastNtpAttempt=millis(); Serial.println("[NTP] Synchronizacja w toku"); configTzTime(TZ_INFO,"pool.ntp.org","time.cloudflare.com","time.google.com"); sntp_set_sync_interval(NTP_SYNC_INTERVAL_MS); }
void TimeManager::loop(){ const unsigned long now=millis(); if(now-lastRtcReadAttempt>=RTC_READ_INTERVAL_MS) pollRtc(); if(ntpUpdatePending) handleNtpUpdate(); if(!ntpSynced&&now-lastNtpAttempt>=NTP_RETRY_INTERVAL_MS){ Serial.println("[NTP] Brak synchronizacji - kolejna proba za 60 s"); startNtpSync(); } }
bool TimeManager::readRtc(DateTime& value){ Wire.beginTransmission(DS3231_ADDRESS); if(Wire.endTransmission()!=0) return false; value=rtc.now(); const uint32_t stamp=value.unixtime(); return stamp>=MIN_VALID_TIMESTAMP&&value.year()>=2023&&value.year()<=2099; }
void TimeManager::pollRtc(bool initialRead){ lastRtcReadAttempt=millis(); DateTime value(static_cast<uint32_t>(0)); const bool success=readRtc(value); if(success){ cachedUtc=value; cachedAtMillis=millis(); consecutiveRtcFailures=0; if(rtcOk){ consecutiveRtcSuccesses=RTC_RECOVERY_THRESHOLD; return; } if(initialRead) consecutiveRtcSuccesses=RTC_RECOVERY_THRESHOLD; else if(consecutiveRtcSuccesses<RTC_RECOVERY_THRESHOLD) ++consecutiveRtcSuccesses; if(consecutiveRtcSuccesses>=RTC_RECOVERY_THRESHOLD){ rtcOk=true; if(!initialRead) Serial.println("[RTC] Communication restored"); } return; } consecutiveRtcSuccesses=0; if(consecutiveRtcFailures<RTC_FAILURE_THRESHOLD){ ++consecutiveRtcFailures; Serial.printf("[RTC] Read error (%u/%u)\n",consecutiveRtcFailures,RTC_FAILURE_THRESHOLD); } if(rtcOk&&consecutiveRtcFailures>=RTC_FAILURE_THRESHOLD){ rtcOk=false; Serial.println("[RTC] Communication lost"); } }
void TimeManager::onNtpSync(struct timeval*){ if(instance) instance->ntpUpdatePending=true; }
void TimeManager::handleNtpUpdate(){ ntpUpdatePending=false; const time_t now=time(nullptr); if(now<MIN_VALID_TIMESTAMP){ Serial.println("[NTP] Otrzymany czas jest niewiarygodny"); return; } ntpSynced=true; lastNtpSyncTimestamp=static_cast<uint32_t>(now); Serial.println("[NTP] Synchronizacja OK"); updateRtcFromSystem(); }
void TimeManager::updateRtcFromSystem(){ const time_t now=time(nullptr); if(now<MIN_VALID_TIMESTAMP){ Serial.println("[RTC] Czas systemowy niewiarygodny - RTC nie zostanie ustawiony"); return; } if(!rtcOk){ Serial.println("[RTC] Brak komunikacji z DS3231 - korekta pominieta"); return; } rtc.adjust(DateTime(static_cast<uint32_t>(now))); cachedUtc=DateTime(static_cast<uint32_t>(now)); cachedAtMillis=millis(); Serial.println("[RTC] DS3231 skorygowany z NTP (UTC)"); }
DateTime TimeManager::getUtcTime() const { if(!rtcOk||cachedUtc.unixtime()<MIN_VALID_TIMESTAMP) return DateTime(static_cast<uint32_t>(0)); const uint32_t elapsed=(millis()-cachedAtMillis)/1000UL; return cachedUtc+TimeSpan(static_cast<int32_t>(elapsed)); }
tm TimeManager::getLocalTime() const { tm result{}; const time_t stamp=static_cast<time_t>(getUtcTime().unixtime()); if(stamp<static_cast<time_t>(MIN_VALID_TIMESTAMP)) return result; localtime_r(&stamp,&result); return result; }
bool TimeManager::isRtcOk() const{return rtcOk;} bool TimeManager::isNtpSynced() const{return ntpSynced;} uint32_t TimeManager::getLastNtpSyncTimestamp() const{return lastNtpSyncTimestamp;}
void TimeManager::printStatus(){ if(!rtcOk){ Serial.println("[TIME] RTC ERROR"); return; } const DateTime utc=getUtcTime(); const tm local=getLocalTime(); Serial.printf("[TIME] UTC %04d-%02d-%02d %02d:%02d:%02d | LOCAL %04d-%02d-%02d %02d:%02d:%02d | RTC:%s | NTP:%s\n",utc.year(),utc.month(),utc.day(),utc.hour(),utc.minute(),utc.second(),local.tm_year+1900,local.tm_mon+1,local.tm_mday,local.tm_hour,local.tm_min,local.tm_sec,rtcOk?"OK":"ERROR",ntpSynced?"OK":"BRAK"); }