[platformio]
default_envs = esp32-s3

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

build_flags =
    -D PROJECT_NAME=\"aquaOneFauna\"
    -D PROJECT_DISPLAY_NAME=\"aquaOne Fauna\"
