[platformio]
default_envs = gassense

[env:gassense]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

lib_ldf_mode = deep+

board_build.flash_size = 4MB
board_upload.flash_size = 4MB

board_build.arduino.memory_type = qio_opi

board_build.partitions = default.csv

build_flags =
    -D GASSENSE_FW_VERSION=\"0.1.0-dev\"
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    bogde/HX711
    adafruit/Adafruit ADS1X15
    adafruit/Adafruit BusIO
    paulstoffregen/OneWire
    milesburton/DallasTemperature

lib_extra_dirs =
    ../AquaCore/aqua_core